# Generated by Django 2.2.5 on 2019-09-21 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=None, max_length=250, null=True, verbose_name='组名')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '团队组名表',
                'verbose_name_plural': '团队组名表',
                'db_table': 'Report_Group',
                'ordering': ['-id', '-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=None, max_length=250, null=True, verbose_name='花名')),
                ('actual_name', models.CharField(blank=None, max_length=250, null=True, verbose_name='真实姓名')),
                ('status', models.BooleanField(null=True, verbose_name='新老员工状态')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.GroupModel', verbose_name='团队组ID')),
            ],
            options={
                'verbose_name': '成员表',
                'verbose_name_plural': '成员表',
                'db_table': 'Report_Person',
                'ordering': ['-id', '-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ReturnDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_visit_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='回访量')),
                ('success_opening_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='成功开场')),
                ('business_introduction_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='业务介绍')),
                ('answer_question_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='解答问题')),
                ('contract_pay_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='约定付款')),
                ('quality_error_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='质检差错数')),
                ('data_time', models.DateField(default=django.utils.timezone.now, verbose_name='数据日期')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.PersonModel', verbose_name='成员ID')),
            ],
            options={
                'verbose_name': '回访数据表',
                'verbose_name_plural': '回访数据表',
                'db_table': 'Report_ReturnData',
                'ordering': ['-id', '-data_time', '-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_addition_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='新加量')),
                ('talkable_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='可聊量')),
                ('work_customer_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='work客户量')),
                ('transaction_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='成交量')),
                ('data_time', models.DateField(default=django.utils.timezone.now, verbose_name='数据日期')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.PersonModel', verbose_name='成员ID')),
            ],
            options={
                'verbose_name': '绩效数据表',
                'verbose_name_plural': '绩效数据表',
                'db_table': 'Report_PerformanceData',
                'ordering': ['-id', '-data_time', '-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='开发量')),
                ('new_customer_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='新客数')),
                ('success_opening_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='成功开场')),
                ('business_introduction_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='业务介绍')),
                ('answer_question_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='解答问题')),
                ('contract_pay_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='约定付款')),
                ('quality_error_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='质检差错数')),
                ('data_time', models.DateField(default=django.utils.timezone.now, verbose_name='数据日期')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.PersonModel', verbose_name='成员ID')),
            ],
            options={
                'verbose_name': '新增数据表',
                'verbose_name_plural': '新增数据表',
                'db_table': 'Report_DevelopmentData',
                'ordering': ['-id', '-data_time', '-date_joined'],
            },
        ),
    ]
