# Generated by Django 2.2.5 on 2019-09-29 01:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancedatamodel',
            name='source',
            field=models.IntegerField(choices=[(1, '回访成交'), (0, '新增成交'), (2, '公海成交')], default=0, verbose_name='数据来源'),
        ),
        migrations.CreateModel(
            name='HighSeasDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_seas_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='公海量')),
                ('success_opening_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='成功开场')),
                ('business_introduction_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='业务介绍')),
                ('answer_question_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='解答问题')),
                ('contract_pay_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='约定付款')),
                ('quality_error_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='质检差错数')),
                ('data_time', models.DateField(default=django.utils.timezone.now, verbose_name='数据日期')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.PersonModel', verbose_name='成员ID')),
            ],
            options={
                'verbose_name': '公海数据表',
                'verbose_name_plural': '公海数据表',
                'db_table': 'Report_HighSeasData',
                'ordering': ['-id', '-data_time', '-date_joined'],
            },
        ),
    ]
