# Generated by Django 2.2.5 on 2019-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_auto_20190929_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedatamodel',
            name='source',
            field=models.IntegerField(choices=[(1, '回访成交'), (2, '公海成交'), (0, '新增成交')], default=0, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='status',
            field=models.IntegerField(choices=[(1, '新员工'), (2, '离职'), (0, '老员工')], default=0, verbose_name='员工状态'),
        ),
    ]
