# Generated by Django 2.2.5 on 2019-10-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_auto_20191009_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedatamodel',
            name='source',
            field=models.IntegerField(choices=[(0, '新增成交'), (1, '回访成交'), (2, '公海成交')], default=0, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='status',
            field=models.IntegerField(choices=[(2, '离职'), (1, '新员工'), (0, '老员工')], default=0, verbose_name='员工状态'),
        ),
    ]
